# Generated by Django 4.1.10 on 2023-10-25 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0123_device_automation_ansible_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomLabel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_by', models.CharField(blank=True, max_length=128, null=True, verbose_name='Created by')),
                ('updated_by', models.CharField(blank=True, max_length=128, null=True, verbose_name='Updated by')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('comment', models.TextField(blank=True, null=True, default='', verbose_name='Comment')),
                ('org_id', models.CharField(blank=True, db_index=True, default='', max_length=36, verbose_name='Organization')),
                ('value', models.CharField(blank=True, max_length=128, null=True, verbose_name='value')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Custom Labels',
                'db_table': 'assets_customlabel',
                'unique_together': {('value',)},
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='custom_labels',
            field=models.ManyToManyField(blank=True, related_name='assets', to='assets.customlabel', verbose_name='Custom Labels'),
        ),
    ]
