# Generated by Django 4.1.10 on 2023-10-19 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0011_remove_redundant_permission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menupermission',
            options={'default_permissions': [], 'permissions': [('view_console', 'Can view console view'), ('view_audit', 'Can view audit view'), ('view_workbench', 'Can view workbench view'), ('view_webterminal', 'Can view web terminal'), ('view_filemanager', 'Can view file manager'), ('view_systemtools', 'Can view System Tools')], 'verbose_name': 'Menu permission'},
        ),
    ]
